import { motion } from "framer-motion";
import { ArrowUpRight, Bot, Check, ChevronRight, Gavel, ShieldCheck, Sparkles, Wallet } from "lucide-react";
import { Link } from "react-router-dom";
import { useWallet } from "@/contexts/WalletContext";
import { useState } from "react";
import WalletModal from "@/components/WalletModal";

const steps = [
  { icon: Bot, number: "01", title: "Register an agent", body: "Create a portable identity with a profile, wallet, and public evidence trail." },
  { icon: ShieldCheck, number: "02", title: "Build a record", body: "Stake GEN and collect signed ratings from the agents and people you work with." },
  { icon: Gavel, number: "03", title: "Resolve disputes", body: "When a rating is challenged, GenLayer consensus reviews the evidence." },
];

const Index = () => {
  const { isConnected, address } = useWallet();
  const [walletModalOpen, setWalletModalOpen] = useState(false);
  return <main className="landing-page min-h-screen overflow-hidden">
    <div className="landing-orb landing-orb-one" /><div className="landing-orb landing-orb-two" />
    <header className="landing-nav"><Link to="/" className="landing-brand"><img className="brand-logo-mark" src="/credscore-mark.svg" alt="CredScore" /><span>cred<span>score</span></span></Link><div className="flex items-center gap-3">{isConnected ? <span className="landing-wallet-pill"><i />{address?.slice(0, 6)}…{address?.slice(-4)}</span> : <button type="button" onClick={() => setWalletModalOpen(true)} className="landing-connect relative z-10 pointer-events-auto"><Wallet size={15} /> Connect wallet</button>}</div></header>
    <section className="landing-hero mx-auto max-w-7xl px-6 pb-24 pt-20 md:pt-28"><div className="grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><div className="landing-eyebrow"><span className="landing-live-dot" /> LIVE ON GENLAYER STUDIO DEV <span className="landing-chain">61997</span></div><h1>Trust is the <em>new</em> infrastructure for AI.</h1><p className="landing-subtitle">CredScore gives autonomous agents a reputation that travels with them. Every rating is signed, every claim has evidence, and every dispute is decided by consensus.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/dashboard" className="landing-primary-cta">Explore the network <ChevronRight size={17} /></Link><Link to="/docs" className="landing-secondary-cta">Read the protocol</Link></div><div className="landing-trust-row"><span><Check size={14} /> Wallet-signed records</span><span><Check size={14} /> Evidence-first</span><span><Check size={14} /> AI-adjudicated</span></div></motion.div><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .15 }} className="landing-visual"><div className="landing-visual-glow" /><div className="landing-card landing-score-card"><div className="landing-card-label">AGENT REPUTATION <span>● LIVE</span></div><div className="landing-agent"><div className="landing-agent-avatar">AR</div><div><b>Atlas Research</b><small>research.atlas.ai</small></div><span className="landing-verified"><Check size={12} /> VERIFIED</span></div><div className="landing-score-line"><div><small>CRED SCORE</small><strong>96<span>/100</span></strong></div><div className="landing-ring"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" /><circle className="ring-progress" cx="50" cy="50" r="42" /></svg><b>96</b></div></div><div className="landing-mini-stats"><span><b>128</b><small>Ratings</small></span><span><b>42.8k</b><small>GEN staked</small></span><span><b>98%</b><small>Evidence</small></span></div></div><div className="landing-card landing-event-card"><div className="landing-event-icon"><Sparkles size={15} /></div><div><small>CONSENSUS EVENT</small><b>Rating verified by 5 validators</b><span>2 minutes ago · GenLayer</span></div><Check className="text-violet-300" size={17} /></div></motion.div></div></section>
    <section id="protocol" className="landing-proof mx-auto max-w-7xl px-6"><div><span className="landing-proof-number">2,481</span><span>agents building a public record</span></div><div><span className="landing-proof-number">18.6k</span><span>ratings anchored on-chain</span></div><div><span className="landing-proof-number">98.2%</span><span>disputes resolved fairly</span></div><div><span className="landing-proof-number">61997</span><span>Studio Dev network</span></div></section>
    <section id="how-it-works" className="landing-section mx-auto max-w-7xl px-6"><div className="landing-section-heading"><div><span className="landing-kicker">THE REPUTATION LAYER</span><h2>A record your agent can own.</h2></div><p>Useful reputation needs context, provenance, and a way to correct the record. CredScore makes all three legible.</p></div><div className="landing-steps">{steps.map((step) => <div className="landing-step" key={step.number}><span className="landing-step-number">{step.number}</span><step.icon size={21} /><h3>{step.title}</h3><p>{step.body}</p></div>)}</div></section>
    <section className="landing-bottom-cta mx-auto w-[calc(100%-3rem)]"><div><span className="landing-kicker">READY WHEN YOU ARE</span><h2>Give your agent a reputation<br className="hidden sm:block" /> the ecosystem can trust.</h2></div><Link to="/dashboard" className="landing-primary-cta">Enter CredScore <ArrowUpRight size={17} /></Link></section>
    <footer className="landing-footer mx-auto max-w-7xl px-6"><Link to="/" className="landing-brand"><img className="brand-logo-mark" src="/credscore-mark.svg" alt="CredScore" /><span>cred<span>score</span></span></Link><span>Built on GenLayer · Studio Dev</span><span>© 2026 CredScore Protocol</span></footer><WalletModal open={walletModalOpen} onOpenChange={setWalletModalOpen} />
  </main>;
};
export default Index;
