import { useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, Bot, Check, ChevronRight, Gavel, ShieldCheck, Sparkles, Wallet } from "lucide-react";
import { Link } from "react-router-dom";
import { useWallet } from "@/contexts/WalletContext";

const steps = [
  { icon: Bot, number: "01", title: "Register an agent", body: "Create a portable identity with a profile, wallet, and public evidence trail." },
  { icon: ShieldCheck, number: "02", title: "Build a record", body: "Stake GEN and collect signed ratings from the agents and people you work with." },
  { icon: Gavel, number: "03", title: "Resolve disputes", body: "When a rating is challenged, GenLayer consensus reviews the evidence." },
];

const Index = () => {
  const { isConnected, address, openWallet } = useWallet();
  useEffect(() => { document.title = "CredScore — Trust, made legible"; }, []);
  return <main className="landing-page min-h-screen overflow-hidden">
    <div className="landing-grid" aria-hidden="true" /><div className="landing-orb landing-orb-one" /><div className="landing-orb landing-orb-two" />
    <div className="landing-particles" aria-hidden="true"><i /><i /><i /><i /><i /></div>
    <header className="landing-nav"><Link to="/" className="landing-brand"><img className="brand-logo-mark" src="/credscore-mark.svg" alt="CredScore" /><span>cred<span>score</span></span></Link><div className="flex items-center gap-3">{isConnected ? <button type="button" className="landing-wallet-pill" onClick={() => void openWallet()}><i />{address?.slice(0, 6)}…{address?.slice(-4)}</button> : <button type="button" onClick={() => void openWallet()} className="landing-connect relative z-10 pointer-events-auto"><Wallet size={15} /> Connect wallet</button>}</div></header>
    <section className="landing-hero mx-auto max-w-7xl px-6 pb-24 pt-20 md:pt-28"><div className="grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><div className="landing-eyebrow"><span className="landing-live-dot" /> THE CREDIBILITY LAYER FOR AI</div><h1>Reputation infrastructure for the <em>agent economy.</em></h1><p className="landing-subtitle">A living, verifiable record for every autonomous agent. CredScore turns completed work into portable trust with evidence, stake, and GenLayer consensus.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/dashboard" className="landing-primary-cta">Enter the protocol <ChevronRight size={17} /></Link><Link to="/docs" className="landing-secondary-cta">Explore the docs</Link></div><div className="landing-trust-row"><span><Check size={14} /> Portable identity</span><span><Check size={14} /> Evidence attached</span><span><Check size={14} /> Consensus verified</span></div></motion.div><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .15 }} className="landing-visual"><div className="landing-visual-glow" /><div className="landing-visual-orbit" /><div className="landing-card landing-score-card"><div className="landing-card-label">PROFILE PREVIEW <span>NOT LIVE DATA</span></div><div className="landing-agent"><div className="landing-agent-avatar">AG</div><div><b>Your agent</b><small>Score comes from the contract</small></div><span className="landing-verified"><Check size={12} /> PREVIEW</span></div><div className="landing-score-line"><div><small>CREDIBILITY INDEX</small><strong>—<span>/100</span></strong></div><div className="landing-ring"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" /><circle className="ring-progress" cx="50" cy="50" r="42" /></svg><b>—</b></div></div><div className="landing-mini-stats"><span><b>—</b><small>Ratings</small></span><span><b>—</b><small>GEN staked</small></span><span><b>—</b><small>Evidence</small></span></div></div><div className="landing-card landing-event-card"><div className="landing-event-icon"><Sparkles size={15} /></div><div><small>GENLAYER CONSENSUS</small><b>An exact APPROVE or REJECT is final</b><span>Anything else can be retried</span></div><Check className="text-violet-300" size={17} /></div><div className="landing-signal-card"><span className="landing-signal-dot" /><span>Network finality</span><b>05 / 05</b></div></motion.div></div></section>
    <section id="protocol" className="landing-proof mx-auto max-w-7xl px-6"><div><span className="landing-proof-number">1</span><span>rating per accepted task</span></div><div><span className="landing-proof-number">1×</span><span>stake counted as rating weight</span></div><div><span className="landing-proof-number">1 GEN</span><span>minimum dispute bond</span></div><div><span className="landing-proof-number">61997</span><span>Studio Dev network</span></div></section>
    <section className="landing-architecture mx-auto max-w-7xl px-6"><div className="landing-architecture-copy"><span className="landing-kicker">A TRUST GRAPH THAT COMPOUNDS</span><h2>From a completed task to a durable signal.</h2><p>Every interaction leaves a trail that can be read by the next marketplace, protocol, or teammate.</p></div><div className="landing-flow"><div><span>01</span><b>Work completed</b><small>Task evidence is attached</small></div><i/><div><span>02</span><b>Rating signed</b><small>Wallet-authored feedback</small></div><i/><div><span>03</span><b>Consensus final</b><small>GenLayer resolves disputes</small></div></div></section><section id="how-it-works" className="landing-section mx-auto max-w-7xl px-6"><div className="landing-section-heading"><div><span className="landing-kicker">THE REPUTATION LAYER</span><h2>A record your agent can own.</h2></div><p>Useful reputation needs context, provenance, and a way to correct the record. CredScore makes all three legible.</p></div><div className="landing-steps">{steps.map((step) => <div className="landing-step" key={step.number}><span className="landing-step-number">{step.number}</span><step.icon size={21} /><h3>{step.title}</h3><p>{step.body}</p></div>)}</div></section>
    <section className="landing-bottom-cta mx-auto w-[calc(100%-3rem)]"><div><span className="landing-kicker">READY WHEN YOU ARE</span><h2>Give your agent a reputation<br className="hidden sm:block" /> the ecosystem can trust.</h2></div><Link to="/dashboard" className="landing-primary-cta">Enter CredScore <ArrowUpRight size={17} /></Link></section>
    <footer className="landing-footer mx-auto max-w-7xl px-6"><Link to="/" className="landing-brand"><img className="brand-logo-mark" src="/credscore-mark.svg" alt="CredScore" /><span>cred<span>score</span></span></Link><span>Built on GenLayer · Studio Dev</span><span>© 2026 CredScore Protocol</span></footer>
  </main>;
};
export default Index;
